---
- stat: path=/var/swap
  register: swap

- block:
  - command: dd if=/dev/zero of=/var/swap count=2048 bs=1MiB
  - command: chmod 600 /var/swap
  - command: mkswap /var/swap
  - command: swapon /var/swap
  when: not swap.stat.exists and ansible_swaptotal_mb < 1
