---
- stat: path={{ drupal_root_path }}/index.php
  register: drupal

- stat: path={{ drupal_root_path }}
  register: parent_dir

- name: Create root directory for drupal.
  file: path={{ drupal_root_path }} state=directory owner=nginx group=nginx mode=0755
  when: not parent_dir.stat.exists
  become: yes

- name: Check if site is already installed.
  command: >
    {{ drush_path }} status bootstrap
    chdir={{ drupal_root_path }}
  register: drupal_site_installed
  failed_when: false
  changed_when: false
  become: no

- block:
  - name: Download Drupal
    get_url: url=https://ftp.drupal.org/files/projects/drupal-{{ drupal_version }}.tar.gz dest=/tmp/drupal-{{ drupal_version }}.tar.gz
  
  - name: Extract archive
    unarchive:
      src: /tmp/drupal-{{ drupal_version }}.tar.gz
      dest: /tmp
      copy: no
    environment:
      LANG: C
      LC_ALL: C
      LC_MESSAGES: C
  
  - name: Move archive
    shell: mv /tmp/drupal-{{ drupal_version }}/* {{ drupal_root_path }}
    notify: restart php-fpm

  - name: Create Drupal database
    mysql_db: name={{ drupal_database_name }} state=present
  
  - name: Create Drupal database user
    mysql_user:
      name: "{{ drupal_database_user }}"
      password: "{{ drupal_database_password }}"
      priv: "{{ drupal_database_name }}.*:ALL"
      host: "{{ drupal_database_host }}"
      state: present
  
  - name: Install Drupal with drush.
    command: >
      {{ drush_path }} site-install {{ drupal_site_install_profile | default('standard') }} -y
      --site-name="{{ drupal_site_name }}"
      --account-name={{ drupal_account_name }}
      --account-pass={{ drupal_account_pass }}
      --db-url=mysql://{{ drupal_database_user }}:{{ drupal_database_password }}@{{ drupal_database_host }}/{{ drupal_database_name }}
      {{ drupal_site_install_extra_args | default([]) | join(" ") }}
      chdir={{ drupal_root_path }}
    notify: restart webserver

  - name: Install modules for drupal
    shell: chdir={{ drupal_root_path }} {{ drush_dir }}/drush -y --default-major={{ drupal_major_version }} dl {{ item }}
    with_items: "{{ drupal_extra_modules }}"
  
  - name: Enable modules for drupal
    shell: chdir={{ drupal_root_path }} {{ drush_dir }}/drush -y en {{ item }}
    with_items: "{{ drupal_enable_modules }}"
  
  - name: Disable modules for drupal
    shell: chdir={{ drupal_root_path }} {{ drush_dir }}/drush -y dis {{ item }}
    with_items: "{{ drupal_disable_modules }}"

  - name: Change ownership of Drupal installation
    file: path={{ drupal_root_path }} owner=nginx group=nginx state=directory recurse=yes
    when: drupal_on_synced_folder == false
  
  when: "'Successful' not in drupal_site_installed.stdout and {{ drupal_site_install }} == true"
