---
- include: redhat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'
  static: no

- include: amazon-linux.yml
  when: ansible_distribution == 'Amazon'
  static: no

- name: Copy php-fpm configuration
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf
  notify: restart php-fpm
