---
- block:
    - name: Disable selinux
      selinux: state=disabled

    - name: Install yum-cron
      package: name=yum-cron state=present

    - name: Initialize yum-cron.conf
      lineinfile:
        dest: /etc/yum/yum-cron.conf
        state: present
        regexp: "^update_cmd = default$"
        line: "update_cmd = security"
        backrefs: yes

    - name: Initialize yum-cron.conf
      lineinfile:
        dest: /etc/yum/yum-cron.conf
        state: present
        regexp: "^apply_updates = no$"
        line: "apply_updates = yes"
        backrefs: yes
  when: ansible_os_family == 'RedHat'

- name: Install firewalld
  package: name=firewalld state=present

- name: Check if firewalld is enabled
  command: systemctl is-enabled firewalld
  register: firewalld_is_enabled
  changed_when: False
  ignore_errors: True # FIXME

- block:
    - name: Start firewalld
      service: name=firewalld state=started enabled=yes

    - name: Setup firewalld
      firewalld: port={{ item }} permanent=true zone=public state=enabled
      with_items: "{{ firewall_allowed_ports }}"

    - name: Reload firewalld
      command: firewall-cmd --reload

    - name: Enable firewalld
      command: systemctl enable firewalld

  when: firewalld_is_enabled.stdout == "disabled"
