---
- name: Install drupal environment
  hosts: all
  become: yes

  vars_files:
    - group_vars/all
    - ../config.yml

  roles:
    - security
    - swap
    - common
    - mysql
    - nginx
    - php-fpm
    - composer
    - drush
    - { role: drupalconsole, when: '"drupalconsole" in extra_features' }
    - { role: nodejs, when: '"nodejs" in extra_features' }
    - { role: jdk, when: '"solr" in extra_features' }
    - { role: solr, when: '"solr" in extra_features' }
    - { role: mautic, when: '"mautic" in extra_features' }
    - drupal
    - cron

  tasks:
    - name: Run configured post-provision shell scripts.
      script: "{{ item }}"
      with_items: "{{ post_provision_scripts }}"
      when: post_provision_scripts is defined
