---
- name: Install python-pip
  become: yes
  package: name={{ item }} state=present
  with_items:
    - python-pip

- name: Install awscli
  become: yes
  pip:
    name: awscli

- name: Create the awscli config directory
  file: >
    path={{ ansible_env.HOME}}/.aws
    state=directory
    mode=0755

- name: Create awscli config
  template: >
    src=config.j2
    dest={{ ansible_env.HOME }}/.aws/config
    mode=0600

- name: Create awscli credentials
  template: >
    src=credentials.j2
    dest={{ ansible_env.HOME }}/.aws/credentials
    mode=0600
