---
- stat: path={{ drupalconsole_path }}
  register: drupalconsole

- block:
  - command: "composer global require drupal/console:{{ drupalconsole_version }}"
  - file: src=~/.composer/vendor/bin/drupal
          dest={{ drupalconsole_path }}
          state=link
  - command: "{{ drupalconsole_path }} init"
  when: not drupalconsole.stat.exists and drupal_major_version == 8
  become: yes
